version: "3.8"

x-airflow-common:
  &airflow-common
  image: apache/airflow:2.9.2    # ✅ ενημερώθηκε η έκδοση
  environment:
    &airflow-env
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
    AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__API__AUTH_BACKENDS: airflow.api.auth.backend.basic_auth
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "true"
    AIRFLOW__CORE__DEFAULT_TIMEZONE: "Europe/Athens"
    _PIP_ADDITIONAL_REQUIREMENTS: ""
  volumes:
    - ../dags:/opt/airflow/dags          # το dags/ που έχεις ήδη
    - ../logs:/opt/airflow/logs
    - ../plugins:/opt/airflow/plugins
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    - postgres
    - redis

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 5s
      retries: 5

  redis:
    image: redis:latest
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5

  airflow-init:
    <<: *airflow-common
    command: >
      bash -c "
        airflow db init &&
        airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin
      "
    restart: on-failure
    depends_on:
      - postgres
      - redis

  webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    depends_on:
      - airflow-init
      - scheduler

  scheduler:
    <<: *airflow-common
    command: scheduler
    depends_on:
      - airflow-init

  worker:
    <<: *airflow-common
    command: celery worker
    depends_on:
      - airflow-init

  # Apache Superset για visualization
  superset:
    image: apache/superset:3.1.0
    container_name: superset
    environment:
      - SUPERSET_SECRET_KEY=your_secret_key_here_change_in_production
      - SUPERSET_CONFIG_PATH=/app/pythonpath/superset_config.py
      - PYTHONPATH=/app/pythonpath:/app/
    ports:
      - "8088:8088"
    volumes:
      - ../superset_config:/app/pythonpath
      - superset_data:/app/superset_home
    depends_on:
      - postgres
    command: >
      bash -c "
        superset fab create-admin --username admin --firstname Admin --lastname User --email admin@superset.com --password admin &&
        superset db upgrade &&
        superset init &&
        superset run -h 0.0.0.0 -p 8088 --with-threads --reload --debugger
      "
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  superset_data:
