#!/bin/bash

# Quick Superset Setup Script for Weather ELT Project
echo "🎨 Setting up Superset for Weather ELT Analysis..."
echo "================================================"

echo "📋 Setup Checklist:"
echo ""
echo "1. 🐳 Start Docker Stack:"
echo "   ./start_stack.sh"
echo ""
echo "2. 🌐 Access Superset:"
echo "   URL: http://localhost:8088"
echo "   Username: admin"
echo "   Password: admin"
echo ""
echo "3. 🔗 Add Snowflake Connection:"
echo "   Go to: Data > Databases > + DATABASE"
echo "   Choose: Snowflake"
echo "   URI: snowflake://AKARAGKIOZAKIS:Akaragkiozakis123@MPXFEBG-AP40156.snowflakecomputing.com/WEATHER_DWH/GOLD_LAYER?warehouse=COMPUTE_WH&role=ACCOUNTADMIN"
echo ""
echo "4. 📊 Create Datasets:"
echo "   - WEATHER_GOLD_DAILY"
echo "   - MOBILITY_GOLD_DAILY"
echo "   - WEATHER_MOBILITY_COMBINED"
echo ""
echo "5. 📈 Recommended Charts:"
echo "   • Time Series: Weather trends over time"
echo "   • Scatter Plot: Temperature vs Mobility correlation"
echo "   • Bar Chart: Precipitation by region"
echo "   • Heat Map: Regional weather patterns"
echo "   • Line Chart: Temperature and mobility changes"
echo ""
echo "6. 📁 Configuration Files:"
echo "   📄 superset_config/snowflake_connection_ready.md - Full connection guide"
echo "   📄 superset_config/database_connections.md - General connection info"
echo "   📄 superset_config/superset_config.py - Superset configuration"
echo ""
echo "================================================"
echo "🎯 Ready to create amazing weather-mobility visualizations!"
echo "📖 For detailed setup, see: superset_config/snowflake_connection_ready.md"